POST http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwQk5meUVJZHNnNHdUYTZra3VnSmpHYjQxQTJLTTBLOFozSnAwWVRIanhRIn0.eyJleHAiOjE2ODczNDQ0MTUsImlhdCI6MTY4NzM0NDExNSwianRpIjoiYzdhNDRmYjctMTE5OC00NTFiLTgxZjgtYTAwZGZkZDdlNjg3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlciIsImF1ZCI6ImVtYWlsbiIsInN1YiI6IjY0ODNkMzQ0LTkyMGEtNGRkYi1iOWUwLTJkMmZmZWQ0ZGY1ZiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImVtYWlsbiIsInNlc3Npb25fc3RhdGUiOiJhY2MzNzllNy04NDE2LTQzOTctYTBiYy1kYmNhM2YyODFiYWMiLCJzY29wZSI6IiIsInNpZCI6ImFjYzM3OWU3LTg0MTYtNDM5Ny1hMGJjLWRiY2EzZjI4MWJhYyJ9.opPqJcljOvzyczpBbLa1fXZVGhQwJxX4MXYfsXY3sBoVKNwv_OHOR6d8rBCqE3_96w4SWPDwPYzMIOzbBxqUitAIlKji_0SJ8fSLRP52zCZ36kD1kygz5o7zyIRLyTPbpxXHHdF_0gMJYC8TsgdYH_YKVIHYSq2xSBQcF3UW2cS48Xsj2VA6rbSHGe8oO1ej9rNfxSS-BcTkDm7ypmVUjRokxPlh6szPiV0vxY6qq83ZK-rZ68PXJWCzaD0LhPSwmWttgTrvL7Qw6TyJbvYLmo-ahegnkA9rPQwQHf1Z_nKuER2-lRxd2e0SM-ee4o9p3jFUhFL7XjqG__HKCD56hA

{
    "name": "name 223",
    "content": "change",
    "emails": ["teste@email.com"]
}

###

GET http://localhost:3000/campaigns/ci82mpo5jf8288qvmke0

###

PATCH http://localhost:3000/campaigns/cancel/ci82j5o5jf82290jmtb0

###

DELETE http://localhost:3000/campaigns/delete/ci82pbg5jf82ahkvedlg

###

POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=lucas&password=123456&grant_type=password