@url = http://localhost:3000/campaigns
@identity_provider = http://localhost:8080

POST {{url}}
Authorization: Bearer {{access_token}}

{
    "name": "name 223",
    "content": "change",
    "emails": ["teste@email.com"]
}

###

GET {{url}}/ci82mpo5jf8288qvmke0
Authorization: Bearer {{access_token}}

###

PATCH {{url}}/cancel/ci82j5o5jf82290jmtb0
Authorization: Bearer {{access_token}}

###

DELETE {{url}}/delete/ci82pbg5jf82ahkvedlg
Authorization: Bearer {{access_token}}

###
# @name token
POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=lucas&password=123456&grant_type=password

###

@access_token = {{token.response.body.access_token}}